version: '3.6'

services:
  backend:
    image: ghcr.io/kordondev/equipment-watchdog-backend:latest-arm64
    container_name: equipment-watchdog-backend
    user: "${UID}:${GID}"
    ports:
      - "8080:8080"
    volumes:
      - ./configuration:/configuration:ro
      - ./data:/data
    restart: always

  frontend:
    image: ghcr.io/kordondev/equipment-watchdog-frontend
    container_name: equipment-watchdog-frontend
    restart: always
    ports:
      - "1080:9000"
    environment:
      - URL=http://localhost:8080/api
